plugins:
  - jest

env:
  node: true
extends: 
  - airbnb-base
  - plugin:jest/recommended
overrides: []
parserOptions:
  ecmaVersion: 2022
  sourceType: module
rules:
  no-console: 0
  import/extensions: # FIXME: remove when rule will be adjusted for new nodejs version
    - error
    - ignorePackages
    - js: always

